#!/usr/bin/env node
/**
 * Publish Pre-Generated Content to App
 *
 * Standalone script that replicates the Content Studio "Publish to App" logic.
 * Copies JSON profiles and narratives from content-studio-data/output/ into
 * public/data/ subdirectories and generates a populated content-manifest.ts.
 *
 * Usage:  node scripts/publish-content.js
 */

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const SCRIPTS_OUTPUT = path.join(ROOT, 'scripts', 'content-studio-data', 'output')
const PUBLIC_DATA = path.join(ROOT, 'public', 'data')
const PUBLIC_IMAGES = path.join(ROOT, 'public', 'images', 'generated')
const SRC_DATA = path.join(ROOT, 'src', 'data')

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
}

function collectIds(dir) {
  if (!fs.existsSync(dir)) return []
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.json'))
    .map(f => f.replace('.json', ''))
    .sort()
}

console.log('[Publish] Starting content publish...')
console.log('[Publish] Source:', SCRIPTS_OUTPUT)
console.log('[Publish] Destination:', PUBLIC_DATA)

const stats = {
  staff: 0,
  partners: 0,
  contacts: 0,
  sponsors: 0,
  driverNarratives: 0,
  teamNarratives: 0,
  preracePools: 0,
  portraits: { staff: 0, partners: 0, contacts: 0 }
}

// ── 1. Copy profiles into category-specific pool directories ──
const profilesDir = path.join(SCRIPTS_OUTPUT, 'profiles')
if (fs.existsSync(profilesDir)) {
  const files = fs.readdirSync(profilesDir).filter(f => f.endsWith('.json'))
  console.log(`[Publish] Found ${files.length} profile files`)
  for (const file of files) {
    let destDir
    if (file.startsWith('staff-')) {
      destDir = path.join(PUBLIC_DATA, 'staff-pool')
      stats.staff++
    } else if (file.startsWith('partner-')) {
      destDir = path.join(PUBLIC_DATA, 'partner-pool')
      stats.partners++
    } else if (file.startsWith('contact-')) {
      destDir = path.join(PUBLIC_DATA, 'contact-pool')
      stats.contacts++
    } else if (file.startsWith('sponsor-')) {
      destDir = path.join(PUBLIC_DATA, 'sponsor-pool')
      stats.sponsors++
    } else {
      destDir = path.join(PUBLIC_DATA, 'profiles')
    }
    ensureDir(destDir)
    fs.copyFileSync(path.join(profilesDir, file), path.join(destDir, file))
  }
} else {
  console.warn('[Publish] No profiles directory found at', profilesDir)
}

// ── 2. Copy narratives into category-specific directories ──
const narrativesDir = path.join(SCRIPTS_OUTPUT, 'narratives')
if (fs.existsSync(narrativesDir)) {
  const files = fs.readdirSync(narrativesDir).filter(f => f.endsWith('.json'))
  console.log(`[Publish] Found ${files.length} narrative files`)
  for (const file of files) {
    let destDir
    if (file.startsWith('driver-')) {
      destDir = path.join(PUBLIC_DATA, 'driver-narratives')
      stats.driverNarratives++
    } else if (file.startsWith('team-')) {
      destDir = path.join(PUBLIC_DATA, 'team-narratives')
      stats.teamNarratives++
    } else if (file.startsWith('prerace-')) {
      destDir = path.join(PUBLIC_DATA, 'prerace-pools')
      stats.preracePools++
    } else if (file.startsWith('track')) {
      destDir = path.join(PUBLIC_DATA, 'tracks')
    } else {
      destDir = path.join(PUBLIC_DATA, 'profiles')
    }
    ensureDir(destDir)
    fs.copyFileSync(path.join(narrativesDir, file), path.join(destDir, file))
  }
} else {
  console.warn('[Publish] No narratives directory found at', narrativesDir)
}

// ── 3. Scan portrait images ──
const portraitDirs = [
  { dir: path.join(PUBLIC_IMAGES, 'portraits', 'staff'), key: 'staff' },
  { dir: path.join(PUBLIC_IMAGES, 'partners'), key: 'partners' },
  { dir: path.join(PUBLIC_IMAGES, 'contacts'), key: 'contacts' }
]
const portraitMap = {}
for (const { dir, key } of portraitDirs) {
  if (fs.existsSync(dir)) {
    for (const file of fs.readdirSync(dir)) {
      if (file.endsWith('.png') || file.endsWith('.jpg')) {
        const id = file.replace(/\.(png|jpg)$/, '')
        portraitMap[id] = `${key}/${file}`
        stats.portraits[key]++
      }
    }
  }
}

// ── 4. Build ID index lists ──
const staffIds = collectIds(path.join(PUBLIC_DATA, 'staff-pool'))
const partnerIds = collectIds(path.join(PUBLIC_DATA, 'partner-pool'))
const contactIds = collectIds(path.join(PUBLIC_DATA, 'contact-pool'))
const sponsorIds = collectIds(path.join(PUBLIC_DATA, 'sponsor-pool'))
const driverNarrativeIds = collectIds(path.join(PUBLIC_DATA, 'driver-narratives'))
const teamNarrativeIds = collectIds(path.join(PUBLIC_DATA, 'team-narratives'))
const preracePoolIds = collectIds(path.join(PUBLIC_DATA, 'prerace-pools'))

// ── 5. Generate TypeScript manifest ──
const manifestTs = `// Auto-generated by publish-content.js — DO NOT EDIT
// Generated: ${new Date().toISOString()}

export const CONTENT_MANIFEST = {
  version: '1.0.0',
  generatedAt: '${new Date().toISOString()}',

  staff: {
    ids: ${JSON.stringify(staffIds, null, 4).replace(/^/gm, '    ').trim()},
    count: ${staffIds.length},
    basePath: '/data/staff-pool'
  },

  partners: {
    ids: ${JSON.stringify(partnerIds, null, 4).replace(/^/gm, '    ').trim()},
    count: ${partnerIds.length},
    basePath: '/data/partner-pool'
  },

  contacts: {
    ids: ${JSON.stringify(contactIds, null, 4).replace(/^/gm, '    ').trim()},
    count: ${contactIds.length},
    basePath: '/data/contact-pool'
  },

  sponsors: {
    ids: ${JSON.stringify(sponsorIds, null, 4).replace(/^/gm, '    ').trim()},
    count: ${sponsorIds.length},
    basePath: '/data/sponsor-pool'
  },

  driverNarratives: {
    ids: ${JSON.stringify(driverNarrativeIds, null, 4).replace(/^/gm, '    ').trim()},
    count: ${driverNarrativeIds.length},
    basePath: '/data/driver-narratives'
  },

  teamNarratives: {
    ids: ${JSON.stringify(teamNarrativeIds, null, 4).replace(/^/gm, '    ').trim()},
    count: ${teamNarrativeIds.length},
    basePath: '/data/team-narratives'
  },

  preracePools: {
    ids: ${JSON.stringify(preracePoolIds, null, 4).replace(/^/gm, '    ').trim()},
    count: ${preracePoolIds.length},
    basePath: '/data/prerace-pools'
  },

  portraits: ${JSON.stringify(portraitMap, null, 2).replace(/^/gm, '  ').trim()},

  stats: {
    staff: ${stats.staff},
    partners: ${stats.partners},
    contacts: ${stats.contacts},
    sponsors: ${stats.sponsors},
    driverNarratives: ${stats.driverNarratives},
    teamNarratives: ${stats.teamNarratives},
    preracePools: ${stats.preracePools},
    totalProfiles: ${stats.staff + stats.partners + stats.contacts + stats.sponsors},
    totalNarratives: ${stats.driverNarratives + stats.teamNarratives + stats.preracePools}
  }
} as const

export type ContentManifest = typeof CONTENT_MANIFEST
`

ensureDir(SRC_DATA)
fs.writeFileSync(path.join(SRC_DATA, 'content-manifest.ts'), manifestTs)

console.log('')
console.log('[Publish] ✓ Complete!')
console.log(`  Staff profiles:     ${stats.staff}`)
console.log(`  Partner profiles:   ${stats.partners}`)
console.log(`  Contact profiles:   ${stats.contacts}`)
console.log(`  Sponsor profiles:   ${stats.sponsors}`)
console.log(`  Driver narratives:  ${stats.driverNarratives}`)
console.log(`  Team narratives:    ${stats.teamNarratives}`)
console.log(`  Pre-race pools:     ${stats.preracePools}`)
console.log(`  Portraits:          staff=${stats.portraits.staff}, partners=${stats.portraits.partners}, contacts=${stats.portraits.contacts}`)
console.log(`  Manifest written to: ${path.join(SRC_DATA, 'content-manifest.ts')}`)
