#!/usr/bin/env python3
"""
Parse authoritative AMS2 layout metadata from a local TSV source file
and emit a typed reference file consumed by src/data/ams2-tracks.ts.

Primary source file:
  data/ams2-layouts-authoritative.tsv
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

SOURCE_FILE = "data/ams2-layouts-authoritative.tsv"


def clean_wiki_markup(value: str) -> str:
    text = value.strip()
    text = text.replace("&nbsp;", " ")
    text = re.sub(r"<br\s*/?>", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"\[\[([^|\]]+)\|([^\]]+)\]\]", r"\2", text)
    text = re.sub(r"\[\[([^\]]+)\]\]", r"\1", text)
    text = re.sub(r"\{\{[^}]+\}\}", "", text)
    text = text.replace("'''", "").replace("''", "")
    text = text.replace("\u00b4", "'")
    return re.sub(r"\s+", " ", text).strip()


def parse_float(value: str) -> float | None:
    raw = value.strip().replace("*", "")
    if not raw:
        return None
    try:
        return float(raw)
    except ValueError:
        return None


def parse_int(value: str) -> int | None:
    raw = value.strip().replace("*", "")
    if not raw:
        return None
    try:
        return int(float(raw))
    except ValueError:
        return None


def parse_year(value: str) -> int | str:
    raw = value.strip()
    if not raw:
        return ""
    try:
        return int(raw)
    except ValueError:
        return clean_wiki_markup(raw)


def extract_table_rows_from_tsv(tsv_text: str) -> list[list[str]]:
    rows: list[list[str]] = []
    for raw_line in tsv_text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.lower().startswith("country\ttrack\tlayout\tyear\tgrade\tlength"):
            continue
        if line.lower() == "plain text":
            continue

        # Primary format: tab-separated
        cells = [clean_wiki_markup(cell) for cell in line.split("\t")]
        if len(cells) < 10:
            # Some lines may use multiple spaces instead of tabs; try fallback split.
            cells = [clean_wiki_markup(cell) for cell in re.split(r"\s{2,}", line)]
        if len(cells) < 10:
            continue

        rows.append(cells[:10])

    return rows


def build_records(rows: list[list[str]]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for cells in rows:
        country, track, layout, year, grade, length, altitude, turns, dlc, default_date = cells
        records.append(
            {
                "country": country,
                "track": track,
                "layout": layout,
                "year": parse_year(year),
                "grade": grade or None,
                "lengthKm": parse_float(length),
                "altitudeM": parse_float(altitude),
                "turns": parse_int(turns),
                "dlc": dlc or None,
                "defaultDate": default_date or None,
            }
        )
    return records


def write_typescript(records: list[dict[str, Any]], target: Path) -> None:
    header = """/**
 * Auto-generated AMS2 authoritative layout metadata from:
 * data/ams2-layouts-authoritative.tsv
 *
 * DO NOT edit this file manually. Run:
 *   python scripts/sync-ams2-layout-reference.py
 */

export interface AMS2LayoutReferenceRecord {
  country: string
  track: string
  layout: string
  year: number | string
  grade?: string | null
  lengthKm?: number | null
  altitudeM?: number | null
  turns?: number | null
  dlc?: string | null
  defaultDate?: string | null
}

export const AMS2_LAYOUT_REFERENCE: AMS2LayoutReferenceRecord[] = """

    content = header + json.dumps(records, ensure_ascii=False, indent=2) + "\n"
    content += "\n"
    target.write_text(content, encoding="utf-8")


def main() -> None:
    project_root = Path(__file__).resolve().parents[1]
    source_file = project_root / SOURCE_FILE
    output_file = project_root / "src" / "data" / "ams2-layout-reference.ts"

    if not source_file.exists():
        raise FileNotFoundError(
            f"Missing source file: {source_file}. Paste your authoritative AMS2 table there first."
        )

    tsv_text = source_file.read_text(encoding="utf-8")
    rows = extract_table_rows_from_tsv(tsv_text)
    records = build_records(rows)
    write_typescript(records, output_file)

    print(f"Generated {len(records)} authoritative layout records from local source")
    print(f"Source: {source_file}")
    print(f"Wrote: {output_file}")


if __name__ == "__main__":
    main()
